### ISSUE TITLE
Option in settings to lock watch face

### ISSUE THREAD

**Issue by bill909** [rootasjey/metrix-fitbit#1]
I love the simplicity of the watch face but I sometimes tap the screen and accidentally change one of the metrics. Is there a way to add a slider in the settings such that the watch face becomes locked unless you want to edit it?

Thanks, 
Bill

**Comment by rootasjey** [comment]
Thank you :)

Yes, I can add a lock option in the mobile settings app to prevent changing something accidentally.
I'll try to have this working on next week.

**Comment by bill909** [comment]
> Thank you :)
> 
> Yes, I can add a lock option in the mobile settings app to prevent changing something accidentally.
> I'll try to have this working on next week.

Awesome. You're the best! Happy New Year!
