### ISSUE TITLE
Clock face won't show the time

### ISSUE THREAD

**Issue by Br3nda** [rootasjey/metrix-fitbit#6]
The metrics on the clock face all become the stair/floor.. See screenshot. Gradually every metric is the stairs. 
![IMG_20191129_080521](https://user-images.githubusercontent.com/12266/69828115-6140ba80-127f-11ea-8ba2-d181f062c2c4.jpg)

**Comment by Br3nda** [comment]
I just now found the readme on github that explains how to configure. Hadn't worked out our from the info in the fitbit app.

 Maybe you can copy some of that info to the settings part of the app.

**Comment by rootasjey** [comment]
Glad you solved it 🙂.
Yeah, I can add some information in the settings about the configuration.
